import "dotenv/config";
import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import * as schema from "./schema";

const connectionString = process.env.DATABASE_URL!;

async function seed() {
  const client = await mysql.createConnection({
    host: new URL(connectionString).hostname,
    port: Number(new URL(connectionString).port) || 3306,
    user: new URL(connectionString).username,
    password: new URL(connectionString).password,
    database: new URL(connectionString).pathname.slice(1),
    ssl: { rejectUnauthorized: false },
  });

  const db = drizzle(client, { schema, mode: "planetscale" });

  console.log("Seeding asset categories...");
  await db.insert(schema.assetCategories).values([
    { name: "Real Estate", slug: "real-estate", description: "Long-term stable real estate investments with locked liquidity", icon: "Building2" },
    { name: "Invoice Financing", slug: "invoice-financing", description: "Short-term invoice discounting with tradable liquidity", icon: "FileText" },
    { name: "Supply Chain Finance", slug: "supply-chain-finance", description: "Liquidity-based supply chain funding with flexible entry/exit", icon: "Truck" },
  ]);

  console.log("Seeding assets...");
  await db.insert(schema.assets).values([
    {
      name: "Cyber City Commercial Tower",
      slug: "cyber-city-commercial-tower",
      categoryId: 1,
      description: "Premium Grade A commercial office space in the heart of Cyber City, Gurgaon. 12% annual yield with long-term lease agreements from Fortune 500 tenants. Stable cash flows with 5-year lock-in period.",
      location: "Cyber City, Gurgaon",
      image: "/assets/re-1.jpg",
      totalValue: "50000000",
      minInvestment: "500000",
      expectedRoi: "12.50",
      duration: 60,
      durationUnit: "months",
      riskLevel: "low",
      status: "active",
      liquidityType: "locked",
      fundingProgress: "72.40",
      fundedAmount: "36200000",
      yieldGenerated: "4500000",
      startDate: new Date("2024-01-15"),
      endDate: new Date("2029-01-15"),
    },
    {
      name: "Palm Grove Residences",
      slug: "palm-grove-residences",
      categoryId: 1,
      description: "Luxury residential development in Whitefield, Bangalore. 180 premium apartments with world-class amenities. Expected 15% ROI through appreciation and rental income.",
      location: "Whitefield, Bangalore",
      image: "/assets/re-2.jpg",
      totalValue: "75000000",
      minInvestment: "1000000",
      expectedRoi: "15.00",
      duration: 48,
      durationUnit: "months",
      riskLevel: "moderate",
      status: "active",
      liquidityType: "locked",
      fundingProgress: "45.80",
      fundedAmount: "34350000",
      yieldGenerated: "2200000",
      startDate: new Date("2024-03-01"),
      endDate: new Date("2028-03-01"),
    },
    {
      name: "TechPark Alpha - Block B",
      slug: "techpark-alpha-block-b",
      categoryId: 1,
      description: "Modern IT/ITES SEZ building with 95% occupancy. Blue-chip tech company tenants with 3+ year leases. Stable 11% yield with annual escalation.",
      location: "HITEC City, Hyderabad",
      image: "/assets/re-1.jpg",
      totalValue: "35000000",
      minInvestment: "250000",
      expectedRoi: "11.25",
      duration: 36,
      durationUnit: "months",
      riskLevel: "low",
      status: "upcoming",
      liquidityType: "locked",
      fundingProgress: "15.20",
      fundedAmount: "5320000",
      yieldGenerated: "0",
      startDate: new Date("2025-06-01"),
      endDate: new Date("2028-06-01"),
    },
    {
      name: "Invoice Pool - Manufacturing Batch A",
      slug: "invoice-pool-manufacturing-a",
      categoryId: 2,
      description: "Portfolio of 45-day invoices from established manufacturing SMEs. Average discount rate of 8.5%. Diversified across 12 companies with strong credit profiles.",
      location: "Multiple Locations",
      image: "/assets/inv-1.jpg",
      totalValue: "8000000",
      minInvestment: "100000",
      expectedRoi: "8.50",
      duration: 45,
      durationUnit: "days",
      riskLevel: "low",
      status: "active",
      liquidityType: "tradable",
      fundingProgress: "88.50",
      fundedAmount: "7080000",
      yieldGenerated: "320000",
      startDate: new Date("2025-01-10"),
      endDate: new Date("2025-02-24"),
    },
    {
      name: " Pharma Distributor Invoice Bundle",
      slug: "pharma-distributor-invoice-bundle",
      categoryId: 2,
      description: "60-day invoices from top pharmaceutical distributors. 10.2% discount rate. Backed by large pharma companies with excellent payment history.",
      location: "Mumbai, Pune, Ahmedabad",
      image: "/assets/inv-1.jpg",
      totalValue: "12000000",
      minInvestment: "200000",
      expectedRoi: "10.20",
      duration: 60,
      durationUnit: "days",
      riskLevel: "moderate",
      status: "active",
      liquidityType: "tradable",
      fundingProgress: "62.30",
      fundedAmount: "7476000",
      yieldGenerated: "480000",
      startDate: new Date("2025-02-01"),
      endDate: new Date("2025-04-02"),
    },
    {
      name: "Invoice Pool - Export Ready",
      slug: "invoice-pool-export-ready",
      categoryId: 2,
      description: "90-day export invoices with letter of credit backing. 12.5% yield. Diversified textile and handicraft exporters with consistent order flow.",
      location: "Surat, Jaipur, Kolkata",
      image: "/assets/inv-1.jpg",
      totalValue: "5000000",
      minInvestment: "150000",
      expectedRoi: "12.50",
      duration: 90,
      durationUnit: "days",
      riskLevel: "moderate",
      status: "active",
      liquidityType: "tradable",
      fundingProgress: "35.60",
      fundedAmount: "1780000",
      yieldGenerated: "95000",
      startDate: new Date("2025-01-20"),
      endDate: new Date("2025-04-20"),
    },
    {
      name: "LogiChain Working Capital Pool",
      slug: "logichain-working-capital-pool",
      categoryId: 3,
      description: "Pooled supply chain finance for 50+ logistics and warehousing SMEs. Daily yield accrual with instant redemption. Average 9.8% annualized return.",
      location: "Pan India",
      image: "/assets/scf-1.jpg",
      totalValue: "20000000",
      minInvestment: "50000",
      expectedRoi: "9.80",
      duration: 1,
      durationUnit: "months",
      riskLevel: "low",
      status: "active",
      liquidityType: "flexible",
      fundingProgress: "78.90",
      fundedAmount: "15780000",
      yieldGenerated: "890000",
      startDate: new Date("2024-06-01"),
      endDate: new Date("2025-06-01"),
    },
    {
      name: "AgriSupply Chain Liquidity Fund",
      slug: "agrisupply-chain-liquidity-fund",
      categoryId: 3,
      description: "Seasonal working capital for agricultural produce aggregators. Weekly settlement cycles. 13.5% yield backed by commodity collateral.",
      location: "Nashik, Indore, Lucknow",
      image: "/assets/scf-2.jpg",
      totalValue: "15000000",
      minInvestment: "100000",
      expectedRoi: "13.50",
      duration: 6,
      durationUnit: "months",
      riskLevel: "moderate",
      status: "active",
      liquidityType: "flexible",
      fundingProgress: "55.40",
      fundedAmount: "8310000",
      yieldGenerated: "620000",
      startDate: new Date("2024-09-01"),
      endDate: new Date("2025-03-01"),
    },
    {
      name: "AutoParts Vendor Finance Pool",
      slug: "autoparts-vendor-finance-pool",
      categoryId: 3,
      description: "Reverse factoring for auto component suppliers to OEMs. 30-day cycles with 8.2% yield. Secured by OEM purchase orders from major manufacturers.",
      location: "Chennai, Pune, Manesar",
      image: "/assets/scf-1.jpg",
      totalValue: "25000000",
      minInvestment: "75000",
      expectedRoi: "8.20",
      duration: 3,
      durationUnit: "months",
      riskLevel: "low",
      status: "upcoming",
      liquidityType: "flexible",
      fundingProgress: "22.10",
      fundedAmount: "5525000",
      yieldGenerated: "0",
      startDate: new Date("2025-04-01"),
      endDate: new Date("2025-07-01"),
    },
  ]);

  console.log("Seeding performance data...");
  const performanceData = [];
  for (let assetId = 1; assetId <= 9; assetId++) {
    for (let month = 0; month < 6; month++) {
      const date = new Date(2024, month + 6, 1);
      performanceData.push({
        assetId,
        date: date,
        navValue: (100 + month * (1 + Math.random() * 2)).toFixed(4),
        yieldAccrued: (month * (0.5 + Math.random() * 1.5)).toFixed(4),
        aum: ((1000000 + month * 50000) * (1 + Math.random() * 0.1)).toFixed(2),
      });
    }
  }
  await db.insert(schema.assetPerformance).values(performanceData as any);

  console.log("Seeding market listings...");
  await db.insert(schema.marketListings).values([
    {
      sellerId: 1,
      assetId: 4,
      investmentId: 1,
      originalAmount: "500000",
      listingPrice: "485000",
      discountRate: "3.00",
      accruedValue: "512000",
      status: "active",
      expiryDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    },
    {
      sellerId: 1,
      assetId: 4,
      investmentId: 2,
      originalAmount: "300000",
      listingPrice: "295000",
      discountRate: "1.67",
      accruedValue: "308000",
      status: "active",
      expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    },
    {
      sellerId: 1,
      assetId: 5,
      investmentId: 3,
      originalAmount: "750000",
      listingPrice: "720000",
      discountRate: "4.00",
      accruedValue: "780000",
      status: "active",
      expiryDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    },
    {
      sellerId: 1,
      assetId: 7,
      investmentId: 4,
      originalAmount: "200000",
      listingPrice: "198000",
      discountRate: "1.00",
      accruedValue: "205000",
      status: "active",
      expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
  ]);

  console.log("Seed complete!");
  await client.end();
}

seed().catch(console.error);
